### ISSUE TITLE
Hspell.linginfo() return an empty list if the given word can only be parsed as having a prefix.

### ISSUE THREAD

**Issue by ninjaaron** [eranroz/HspellPy#3]
Title pretty much says it all.

how it works in the shell (hspell 1.2 and 1.3):
```bash
$ hsp -l <<< כעב
צירוף חוקי: כ+עב
	עב(ע,ז,יחיד)
	עב(ע,ז,יחיד,סמיכות)
```
(`hsp` is my wrapper script that converts between the system locale and ISO-8859-8)

how it works in Python (3.6):
```python
>>> from HspellPy import Hspell
>>> hs = Hspell(linguistics=True)
>>> hs.linginfo('כעב')
[]
```

Thanks for this lib, by the way. It's very useful for a project I'm working on. I was going to send a patch, but then I discovered this stuff is all C and I don't have a clue about that. Sorry I can't be more helpful. 

(P.S. the current behavior is actually very convenient for my project, since I'm testing exactly whether the form exists by itself or it's a prefix, but I figured you'd like to know)

**Comment by eranroz** [comment]
Thank you for the comment.
1. You should use hs.enum_splits to get the baseword, which can be used for linginfo. 
2. However, I find it convenient to include this functionality into linginfo - so I added a new parameter split_prefix.

The code and the package were updated

**Comment by ninjaaron** [comment]
Thanks! will do! (The current behavior is actually perfect for what I'm doing)

I don't know how I missed `.enum_splits()` in the readme. Must have totally glossed over it.
